// ============================================================
// /api/account/api-keys/[id]
//
//   PATCH  — update a key's scopes.
//   DELETE — revoke a key.
//
// Both admin+, enforced here and by the `api_keys_update` RLS
// policy.
//
// PATCH only ever touches `scopes` — a key's secret is never
// re-shown or regenerated by this route, so widening what a key can
// do (e.g. adding a scope for a new integration) doesn't force
// rotating the credential everywhere it's already configured.
//
// Revocation (DELETE) is a soft revoke: sets `revoked_at` rather than
// deleting the row, so the key's name/prefix stay visible in the
// roster as an audit trail ("this key existed and was turned off")
// and so the auth path's liveness check (`findActiveKeyByHash`
// filters revoked rows) starts rejecting it immediately.
// ============================================================

import { NextResponse } from 'next/server';

import { requireRole, toErrorResponse } from '@/lib/auth/account';
import { normalizeScopes } from '@/lib/api-keys/scopes';
import {
  checkRateLimit,
  rateLimitResponse,
  RATE_LIMITS,
} from '@/lib/rate-limit';

const SAFE_COLUMNS =
  'id, name, key_prefix, scopes, last_used_at, expires_at, revoked_at, created_at';

export async function PATCH(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const ctx = await requireRole('admin');

    const limit = checkRateLimit(
      `admin:apiKeyUpdate:${ctx.userId}`,
      RATE_LIMITS.adminAction
    );
    if (!limit.success) return rateLimitResponse(limit);

    const { id } = await params;

    const body = (await request.json().catch(() => null)) as {
      scopes?: unknown;
    } | null;
    const scopes = normalizeScopes(body?.scopes ?? []);
    if (scopes === null) {
      return NextResponse.json(
        { error: "'scopes' must be an array of known scope strings" },
        { status: 400 }
      );
    }

    // Scope the update by account_id as well as id so an admin can
    // never edit another account's key by guessing a UUID (RLS
    // already enforces this; belt-and-braces, and makes "0 rows
    // updated → 404" precise). A revoked key can't be un-revoked by
    // this route — only DELETE touches `revoked_at`.
    const { data, error } = await ctx.supabase
      .from('api_keys')
      .update({ scopes })
      .eq('id', id)
      .eq('account_id', ctx.accountId)
      .is('revoked_at', null)
      .select(SAFE_COLUMNS)
      .maybeSingle();

    if (error) {
      console.error('[PATCH /api/account/api-keys/[id]] error:', error);
      return NextResponse.json(
        { error: 'Failed to update API key' },
        { status: 500 }
      );
    }
    if (!data) {
      return NextResponse.json(
        { error: 'API key not found or revoked' },
        { status: 404 }
      );
    }

    return NextResponse.json({ key: data });
  } catch (err) {
    return toErrorResponse(err);
  }
}

export async function DELETE(
  _request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const ctx = await requireRole('admin');

    const limit = checkRateLimit(
      `admin:apiKeyRevoke:${ctx.userId}`,
      RATE_LIMITS.adminAction
    );
    if (!limit.success) return rateLimitResponse(limit);

    const { id } = await params;

    // Scope the update by account_id as well as id so an admin can
    // never revoke another account's key by guessing a UUID. (RLS
    // already enforces this; the explicit filter is belt-and-braces
    // and makes the "0 rows updated → 404" path precise.)
    const { data, error } = await ctx.supabase
      .from('api_keys')
      .update({ revoked_at: new Date().toISOString() })
      .eq('id', id)
      .eq('account_id', ctx.accountId)
      .is('revoked_at', null)
      .select('id')
      .maybeSingle();

    if (error) {
      console.error('[DELETE /api/account/api-keys/[id]] error:', error);
      return NextResponse.json(
        { error: 'Failed to revoke API key' },
        { status: 500 }
      );
    }
    if (!data) {
      // Either no such key in this account, or it was already revoked.
      return NextResponse.json(
        { error: 'API key not found or already revoked' },
        { status: 404 }
      );
    }

    return NextResponse.json({ success: true });
  } catch (err) {
    return toErrorResponse(err);
  }
}
